[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  # Configurações de build
  NODE_ENV = "production"
  NEXT_TELEMETRY_DISABLED = "1"
  # Desabilitar scanning de secrets para pastas específicas
  SECRETS_SCAN_OMIT_PATHS = ".next/**,.netlify/**,node_modules/**,public/**,dist/**,.env.netlify,.env.production"
  # Permitir apenas secrets específicos
  SECRETS_SCAN_OMIT_KEYS = "MY_AWS_S3_BUCKET,MY_AWS_REGION"

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

# Headers para otimização
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

# Redirects para Next.js
[[redirects]]
  from = "/_next/image"
  to = "/.netlify/images?url=:url&w=:width&q=:quality"
  status = 200
  query = { q = ":quality", url = ":url", w = ":width" }

# Plugin Next.js
[[plugins]]
  package = "@netlify/plugin-nextjs"